/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg;

import com.omertron.themoviedbapi.model.MovieDb;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Container;
import java.awt.Graphics;
import java.awt.List;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.LinkedList;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author flavio-silva
 */
public class NewJDialog extends javax.swing.JDialog {

    private BufferedImage imagem;
    AreaImagem areaImagem;

    /**
     * Creates new form NewJDialog
     */
    public NewJDialog(java.awt.Frame parent, boolean modal, String nomeFigura) {

        super(parent, modal);
        initComponents();
        this.getRootPane().setDefaultButton(jButton1);
        this.setTitle(nomeFigura);

        Container c = getContentPane();
        c.setLayout(new BorderLayout());

        areaImagem = new AreaImagem();
        c.add(areaImagem, BorderLayout.CENTER);

        LinkedList<String> ls = new LinkedList<String>();
        ls.add("macaco");
        ls.add("banana");
        ls.add("laura");
        ls.add("bernardo");
        ls.add("mamae");
        ls.add("papai");
        ls.add("flavio");
        ls.add("flavia");
        ls.add("clara");
        ls.add("inter");
        ls.add("chaves");
        ls.add("gumball");
        ls.add("porco");
        ls.add("vovo");
        ls.add("aline");
        ls.add("pepa");
        ls.add("davi");
        ls.add("ziro");
                
        String fileName = "erro";
        for( String s: ls){
            if( nomeFigura.toLowerCase().equals(s)){
                fileName = s;
            }
        }
        try {
            File file = new File(fileName+".jpg");
            imagem = ImageIO.read(file);

        } catch (IOException exc) {
            JOptionPane.showMessageDialog(null,
                    "Erro ao carregar a imagem: "
                    + exc.getMessage());
        }

        if (imagem != null) {
            areaImagem.imagem = imagem;
            areaImagem.repaint();
        }

        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(".");
        setBackground(Color.BLACK);

        jButton1.setText("Voltar...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(728, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(677, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}

// Sub-classe de JPanel para exibir a imagem
class AreaImagem extends JPanel {

    public BufferedImage imagem;

    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);

        // desenha a imagem no JPanel
        g.drawImage(imagem, 0, 0, this);
    }
}
